site_name: Rackio
site_description: 'Documentation for Rackio, the Python Framework for Automation and Control.'
site_url: 'http://rackio-framework.rtfd.io/'
site_author: https://github.com/rack-io/rackio-documentation/graphs/contributors
repo_url: http://github.com/rack-io/rackio-documentation
remote_branch: master

nav:
  - Getting Started:
    - Home: index.md
    - Getting Started: cli.md
  - User Guide:
    - Data Repository: data.md
    - Controls and Rules: control.md
    - State Machine: state.md
    - Continous Tasks: task.md
    - Logging: logging.md
    - Alarms: alarm.md
    - Observers: observer.md
    - Scheduler: scheduler.md
    - Events: event.md
    - Admin: admin.md
  - API Reference:
    - Rackio: rackio-api.md

theme: material

extra:
  social:
    - type: 'github'
      link: 'https://github.com/rack-io'

google_analytics:
  - 'UA-125411854-3'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

